name: simple_auth_flutter
description: Simple Auth is the simplest way to authenticate your users/apis. This plugin will securely store tokens/credentials as well as automatically present login UI when needed.
version: 2.0.11
author: James Clancey <james.clancey@gmail.com>
homepage: https://github.com/clancey/simple_auth

publish_to: 'none'

environment:
    sdk: '>=2.12.0 <3.0.0'
    flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  simple_auth: ^2.0.10

dependency_overrides:
  simple_auth:
    path: ../simple_auth


flutter:
  plugin:
    platforms:
      android:
        package: clancey.simpleauth.simpleauthflutter
        pluginClass: SimpleAuthFlutterPlugin
      ios:
        pluginClass: SimpleAuthFlutterPlugin
      macos:
        pluginClass: SimpleAuthFlutterPlugin
      web:
        pluginClass: SimpleAuthFlutterWeb
        fileName: simple_auth_flutter_web.dart
